@startuml

class App

App -- Calculator

class Calculator {
    --
    isEditing:Bool
    ingredientList:Ingredient[]
}

Calculator -- FoodSelect
Calculator -- IngredientList
Calculator -- Pie

class FoodSelect {
    selectFood(food:Food)
    --
    searchText:String
    isSearching:Bool
    foodList:Food[]
    isSuggestionContainerVisible:Bool
    selectedFoodIndex:Number
}

class IngredientList {
    isEditing:Bool
    ingredientList:Ingredient[]
    saveIngredient(ingredient:Ingredient)
    removeIngredient(index:Number)
    --
}

IngredientList -- IngredientItem

class IngredientItem {
    index:Number
    ingredient:Ingredient
    isEditing:Bool
    saveIngredient(ingredient:Ingredient)
    removeIngredient(index:Number)
    --
    amount:Number
    unitName:String
}

class Pie {
    ingredientList:Ingredient[]
}

@enduml